**Consider the following Python dictionary data and Python list labels:**

data = {'birds': ['Cranes', 'Cranes', 'plovers', 'spoonbills', 'spoonbills', 'Cranes', 'plovers', 'Cranes', 'spoonbills', 'spoonbills'],
        'age': [3.5, 4, 1.5, np.nan, 6, 3, 5.5, np.nan, 8, 4],
        'visits': [2, 4, 3, 4, 3, 4, 2, 2, 3, 2],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Question 1. Create a DataFrame birds from this dictionary data which has the
            index labels.
Answer : import pandas ans numpy
         ph.Dataframe() is used to convert dictionary into a Dataframe
         data provides the column value
         index label assigns the row label (a to j)

In [ ]:
import pandas as pd
import numpy as np

data = {'birds': ['Cranes', 'Cranes', 'plovers', 'spoonbills', 'spoonbills', 'Cranes', 'plovers', 'Cranes', 'spoonbills', 'spoonbills'],
        'age': [3.5, 4, 1.5, np.nan, 6, 3, 5.5, np.nan, 8, 4],
        'visits': [2, 4, 3, 4, 3, 4, 2, 2, 3, 2],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
        }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

birds = pd.DataFrame(data, index=labels)
birds

        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
c     plovers  1.5       3       no
d  spoonbills  NaN       4      yes
e  spoonbills  6.0       3       no
f      Cranes  3.0       4       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no

question 2. Display a summary of the basic information about birds DataFrame
            and its data.

Answer :using info() method its provides basic information of Dataframe like
        class type => type of dataframe
        index => label of row (a to j)
        data colums => total 4 columns
        non null count =>number of non missing value
        data type =>like object,int64,float64  
        memory usage => show how much memory the DataFrame consumes

In [ ]:
import pandas as pd

birds = pd.DataFrame(data, index=labels)
#birds.describe()
birds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   birds     10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

question 3. Print the first 2 rows of the birds dataframe.

Answer :birds,head(2) its displays the first 2 rows of the DataFrame

In [ ]:
birds.head(2)

    birds  age  visits priority
a  Cranes  3.5       2      yes
b  Cranes  4.0       4      yes

Question 4. Print all the rows with only 'birds' and 'age' columns from the   
            dataframe**

Answer :first [] tells pandas we are selecting columns
        birds['birds', 'age'] list of columns we want
        so its means ...give me only birds column and age column

In [ ]:
import pandas as pd
import numpy as np

data = {'birds': ['Cranes', 'Cranes', 'plovers', 'spoonbills', 'spoonbills', 'Cranes', 'plovers', 'Cranes', 'spoonbills', 'spoonbills'],
        'age': [3.5, 4, 1.5, np.nan, 6, 3, 5.5, np.nan, 8, 4],
        'visits': [2, 4, 3, 4, 3, 4, 2, 2, 3, 2],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
        }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

birds = pd.DataFrame(data, index=labels)

birds[['birds', 'age']]

        birds  age
a      Cranes  3.5
b      Cranes  4.0
c     plovers  1.5
d  spoonbills  NaN
e  spoonbills  6.0
f      Cranes  3.0
g     plovers  5.5
h      Cranes  NaN
i  spoonbills  8.0
j  spoonbills  4.0

Question 5. select [2, 3, 7] rows and in columns ['birds', 'age', 'visits']

Answer : loc means location by label
        its secelct data using
         row names(index label)
         columns name

In [ ]:
print(birds.loc[['c', 'd', 'h']][['birds', 'age', 'visits']])

        birds  age  visits
c     plovers  1.5       3
d  spoonbills  NaN       4
h      Cranes  NaN       2

question 6. select the rows where the number of visits is less than 4

Answer :birds['visits'] < 4 This creates a condition (True/False) for each row
        birds[...] inside the brackets we pass condition
        so only row where condition is True are selected

In [ ]:
print(birds[birds['visits'] < 4])

        birds  age  visits priority
a      Cranes  3.5       2      yes
c     plovers  1.5       3       no
e  spoonbills  6.0       3       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no

Question 7. select the rows with columns ['birds', 'visits'] where the age is
            missing i.e NaN

Answer : birds['age'].isna() this checks where age is missing(NaN)
          birds[ ... ] only row where condition is True are selected
          [['birds', 'visits']] from filtered row only these columns birds and visits

In [ ]:
print(birds[birds['age'].isna()][['birds', 'visits']])

        birds  visits
d  spoonbills       4
h      Cranes       2

question 8. Select the rows where the birds is a Cranes and the age is less
            than 4
Answer :(birds['birds'] == 'Cranes') checks each row if birds is cranes is true
        otherwise false
        (birds['age] < 4) if age is less than 4 is true otherwise false
        &(AND operater) combine both condition
        only row where both are true will be selected
        birds[ ... ] filters the Dataframe based on the combined condition

In [ ]:
print(birds[(birds['birds'] == 'Cranes') & (birds['age'] < 4)])

    birds  age  visits priority
a  Cranes  3.5       2      yes
f  Cranes  3.0       4       no

Question 9. Select the rows the age is between 2 and 4(inclusive)

Answer :create two condition
        age >= 2 & age <= 4 and combine them using AND(&)
        only the row where age is 2, 3 or 4 will be selected
        all other row will be removed

In [ ]:
birds[(birds['age'] >= 2) & (birds['age'] <= 4)]
#birds[birds['age'].between(2,4)]

        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
f      Cranes  3.0       4       no
j  spoonbills  4.0       2       no

Question 10. Find the total number of visits of the bird Cranes

Answer : birds['birds'] == 'Cranes' this selects only the row where bird name
         is Cranes
         ['visits'] from those filtered row we take only the visits value
         .sum() add all the visits values togather

In [ ]:
birds[birds['birds'] == 'Cranes']['visits'].sum()

np.int64(12)

Question 11. Calculate the mean age for each different birds in dataframe.

Answer : birds.groupby('birds') this group the DataFrame based on each uniqe
        birds type (ex. Cranes, plovers, spoonbills)
        ['age'] from each group we take only the age values
        .mean() the calculate the avareg age for each birds

In [ ]:
birds.groupby('birds')['age'].mean()

#birds['age'].mean()

birds
Cranes        3.5
plovers       3.5
spoonbills    6.0
Name: age, dtype: float64

Question 12. Append a new row 'k' to dataframe with your choice of values for
             each column. Then delete that row to return the original DataFrame.

Answer :loc['k'] creates a new row with index label 'k'
        Inside the list [ ], we give values for each column
        (like birds, age, visits, priority)
        drop('k') removes the row with index 'k'
        inplace=True ensures the change is made directly in the original DataFrame

In [ ]:
# Append a new row 'k'
birds.loc['k'] = ['Cranes', 6, 4.5, 'yes']
birds

#birds.drop('k', inplace=True)
#birds

        birds  age  visits priority
a      Cranes  3.5     2.0      yes
b      Cranes  4.0     4.0      yes
c     plovers  1.5     3.0       no
d  spoonbills  NaN     4.0      yes
e  spoonbills  6.0     3.0       no
f      Cranes  3.0     4.0       no
g     plovers  5.5     2.0       no
h      Cranes  NaN     2.0      yes
i  spoonbills  8.0     3.0       no
j  spoonbills  4.0     2.0       no
k      Cranes  6.0     4.5      yes

In [ ]:
# Delete that row 'k'
birds.drop('k', inplace=True)
birds

        birds  age  visits priority
a      Cranes  3.5     2.0      yes
b      Cranes  4.0     4.0      yes
c     plovers  1.5     3.0       no
d  spoonbills  NaN     4.0      yes
e  spoonbills  6.0     3.0       no
f      Cranes  3.0     4.0       no
g     plovers  5.5     2.0       no
h      Cranes  NaN     2.0      yes
i  spoonbills  8.0     3.0       no
j  spoonbills  4.0     2.0       no

Question 13. Find the number of each type of birds in dataframe (Counts)

Answer : birds['birds'] this gives all birds name from dataFrame
         .value_counts() counts how many time each bird appears

In [ ]:
birds['birds'].value_counts()

birds
Cranes        4
spoonbills    4
plovers       2
Name: count, dtype: int64

Question 14. Sort dataframe (birds) first by the values in the 'age' in
              decending order, then by the value in the 'visits' column in ascending order.
Answer : sort_values() function is used to sort the DataFrame
          by=['age', 'visits'] first sort by age then sort by visits
          ascending=[False, True]
          False → sort age in descending order (highest to lowest)
          True → sort visits in ascending order (lowest to highest)

In [ ]:
birds.sort_values(by=['age', 'visits'], ascending=[False, True])

        birds  age  visits priority
i  spoonbills  8.0       3       no
e  spoonbills  6.0       3       no
g     plovers  5.5       2       no
j  spoonbills  4.0       2       no
b      Cranes  4.0       4      yes
a      Cranes  3.5       2      yes
f      Cranes  3.0       4       no
c     plovers  1.5       3       no
h      Cranes  NaN       2      yes
d  spoonbills  NaN       4      yes

Question 15. Replace the priority column values with'yes' should be 1 and 'no'
            should be 0
  
Answer :birds['priority'] selects the priority column
        .map({...}) replaces values using a dictionary
        'yes' is replaced with 1
        'no' is replaced with 0

In [ ]:
birds = pd.DataFrame(data, index=labels)

birds['priority'] = birds['priority'].map({'yes':1, 'no':0})

birds

        birds  age  visits  priority
a      Cranes  3.5       2         1
b      Cranes  4.0       4         1
c     plovers  1.5       3         0
d  spoonbills  NaN       4         1
e  spoonbills  6.0       3         0
f      Cranes  3.0       4         0
g     plovers  5.5       2         0
h      Cranes  NaN       2         1
i  spoonbills  8.0       3         0
j  spoonbills  4.0       2         0

Question 16. In the 'birds' column, change the 'Cranes' entries to 'trumpeters'.
              
Answer :birds['birds'] This selects the 'birds' column from the DataFrame.
        .replace('Cranes', 'trumpeters')
        This function searches for all values equal to "Cranes"
        and replaces them with "trumpeters".

In [ ]:
birds['birds'] = birds['birds'].replace('Cranes', 'trumpeters')
birds

        birds  age  visits  priority
a  trumpeters  3.5       2         1
b  trumpeters  4.0       4         1
c     plovers  1.5       3         0
d  spoonbills  NaN       4         1
e  spoonbills  6.0       3         0
f  trumpeters  3.0       4         0
g     plovers  5.5       2         0
h  trumpeters  NaN       2         1
i  spoonbills  8.0       3         0
j  spoonbills  4.0       2         0